[project]
name = "t2d-baseline-paper"
version = "0.0.1"
description = "PSYCOP model training utilities"
authors = [{name = "Martin Bernstorff", email = "martinbernstorff@gmail.com"}]

requires-python = ">=3.8.0"

dependencies = [
    "pandas>=1.4.3,<1.5.0",
    "psycop-model-training>=0.31.0,<0.32.0",
]

[project.optional-dependencies]
dev = [
    "pre-commit>=2.19.0,<2.19.1",
]

[build-system]
requires = ["setuptools>=61.0.0", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[tool.coverage.run]
omit = [
    "**/tests/*",
    "**/_vendorized/*",
    "**/about.py",
]

exclude_lines = [
    "pragma: no cover",
    # Don't complain about missing debug-only code:
    "def __unicode__",
    "def __repr__",
    "if self.debug",
    # Don't complain if tests don't hit defensive assertion code:
    "raise AssertionError",
    "raise NotImplementedError",
    # Don't complain if non-runnable code isn't run:
    "if 0:",
    "if __name__ == .__main__.:",
]

[tool.mypy]
ignore_missing_imports = true

[tool.pylint]
load-plugins = "pylint.extensions.docparams,pylint.extensions.code_style,pylint.extensions.for_any_all,pylint.extensions.typing"
good-names = "df,p,f,d,e,n,k,i,v,y_,X,y"
disable = "too-many-lines,line-too-long,missing-raises-doc,no-self-argument,unused-wildcard-import,wildcard-import,no-else-return,too-many-arguments,redefined-outer-name,c-extension-no-member,wrong-import-order,import-outside-toplevel,unused-import,wrong-import-position,deprecated-typing-alias,missing-module-docstring"
extension-pkg-allow-list = "wandb,pydantic"

[tool.pylint.'MESSAGES CONTROL']
extension-pkg-whitelist = "pydantic"

[tool.pytest.ini_options]
markers = [
    "pre_push_test: Tests run on push. Should be as minimal as possible to maintain fast push speeds.",
]
pythonpath = [
  "."
]


[tool.isort]
known_third_party = ["wandb"]

[tool.semantic_release]
branch = "main"
version_variable = [
    "pyproject.toml:version"
]
upload_to_pypi = false
upload_to_release = true
build_command = "python -m pip install build; python -m build"

[tool.pytest-xdist]
n = 4

[tool.pyright]